modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    modId="mc_fishing_pond"
    version="${mod_version}"
    displayName="MC Fishing Pond"
    logoFile="icon.png"
    description="""
A fishing expansion mod for Minecraft.
"""

[[mixins]]
config="mc_fishing_pond-common.mixins.json"

[[dependencies.mc_fishing_pond]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mc_fishing_pond]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"
